import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const envPath = path.join(root, '.env');
const secret = () => crypto.randomBytes(48).toString('base64url');

const secureDefaults = new Map([
  ['MANEFLOW_API_TOKEN', secret],
  ['MANEFLOW_ADMIN_TOKEN', secret],
  ['MANEFLOW_SERVICE_TOKEN', secret],
  ['PROVIDER_WEBHOOK_SECRET', secret],
  ['EBAY_OAUTH_STATE_SECRET', secret],
]);

const ordinaryDefaults = new Map([
  ['PORT', '4321'],
  ['HOST', '127.0.0.1'],
  ['PUBLIC_BASE_URL', 'http://127.0.0.1:4321'],
  ['RELEASE_CHANNEL', 'production-foundation-beta'],
  ['NODE_ENV', 'development'],
  ['MANEFLOW_DEMO_MODE', 'true'],
  ['MANEFLOW_ALLOW_GUEST_WRITES', 'false'],
  ['MANEFLOW_ALLOW_PUBLIC_SIGNUPS', 'true'],
  ['MANEFLOW_REQUIRE_EMAIL_VERIFICATION', 'false'],
  ['MANEFLOW_EXPOSE_DEV_TOKENS', 'false'],
  ['MANEFLOW_ACCOUNT_TOKEN_MINUTES', '60'],
  ['MANEFLOW_SESSION_DAYS', '30'],
  ['MANEFLOW_BOOTSTRAP_ADMIN_EMAIL', 'memphiscardcompany@gmail.com'],
  ['ALLOWED_ORIGINS', ''],
  ['MAX_REQUEST_BYTES', '30000000'],
  ['MANEFLOW_STATE_FILE', '.runtime/state.json'],
  ['STORAGE_MODE', 'json'],
  ['DATABASE_URL', ''],
  ['DATABASE_SSL', 'false'],
  ['DATABASE_POOL_MAX', '20'],
  ['DATABASE_IDLE_TIMEOUT_MS', '30000'],
  ['DATABASE_CONNECT_TIMEOUT_MS', '10000'],
  ['DATABASE_STATEMENT_TIMEOUT_MS', '15000'],
  ['MANEFLOW_EMBEDDING_MODEL_NAME', 'siglip2-so400m-card-front-v1'],
  ['MANEFLOW_EMBEDDING_MODEL_VERSION', '1'],
  ['MANEFLOW_HNSW_EF_SEARCH', '100'],
  ['CACHE_MODE', 'memory'],
  ['REDIS_URL', ''],
  ['MANEFLOW_LOCAL_OCR_ENABLED', 'true'],
  ['MANEFLOW_LOCAL_OCR_PROVIDER', 'auto'],
  ['MANEFLOW_LOCAL_OCR_QUEUE_CAPACITY', '4'],
  ['MANEFLOW_LOCAL_OCR_TIMEOUT_MS', '20000'],
  ['MANEFLOW_VISION_WORKER_URL', 'http://127.0.0.1:8741'],
  ['MANEFLOW_CORE_URL', 'http://127.0.0.1:4321'],
  ['MANEFLOW_CORE_TIMEOUT_SECONDS', '12'],
  ['MANEFLOW_DATA_DIR', '.runtime/vision-data'],
  ['CARD_DETECTOR_BACKEND', 'auto'],
  ['CARD_DETECTOR_MODEL_PATH', ''],
  ['MANEFLOW_EMBEDDING_ENABLED', 'false'],
  ['MANEFLOW_EMBEDDING_MODEL_PATH', ''],
  ['MANEFLOW_EMBEDDING_EXECUTION_PROVIDER', 'auto'],
  ['MANEFLOW_EMBEDDING_INPUT_SIZE', '384'],
  ['MANEFLOW_EMAIL_WEBHOOK_URL', ''],
  ['MANEFLOW_EMAIL_WEBHOOK_SECRET', ''],
  ['OPENAI_API_KEY', ''],
  ['OPENAI_VISION_MODEL', ''],
  ['PSA_API_KEY', ''],
  ['EBAY_CLIENT_ID', ''],
  ['EBAY_CLIENT_SECRET', ''],
  ['EBAY_ENVIRONMENT', 'production'],
  ['EBAY_USER_ACCESS_TOKEN', ''],
  ['EBAY_USER_ACCESS_TOKEN_EXPIRES_AT', ''],
  ['EBAY_REFRESH_TOKEN', ''],
  ['EBAY_REDIRECT_URI_NAME', ''],
  ['EBAY_MARKETPLACE_ID', 'EBAY_US'],
  ['EBAY_MARKETPLACE_INSIGHTS_ENABLED', 'false'],
  ['EBAY_OAUTH_STATE_TTL_MS', '600000'],
  ['JUSTTCG_API_KEY', ''],
  ['SPORTSCARDSPRO_API_TOKEN', ''],
  ['TCGPLAYER_PUBLIC_KEY', ''],
  ['TCGPLAYER_PRIVATE_KEY', ''],
]);

function parseEnv(text) {
  const values = new Map();
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const separator = line.indexOf('=');
    if (separator <= 0) continue;
    values.set(line.slice(0, separator).trim(), line.slice(separator + 1));
  }
  return values;
}

let existing = '';
try {
  existing = await fs.readFile(envPath, 'utf8');
} catch (error) {
  if (error.code !== 'ENOENT') throw error;
}

const parsed = parseEnv(existing);
const additions = [];
for (const [key, createValue] of secureDefaults) {
  if (!parsed.has(key) || parsed.get(key).trim() === '') additions.push(`${key}=${createValue()}`);
}
for (const [key, value] of ordinaryDefaults) {
  if (!parsed.has(key)) additions.push(`${key}=${value}`);
}

if (!existing) {
  const header = '# Generated by ManeFlow first-run setup\n# Provider credentials remain local and are never added to release archives.\n';
  await fs.writeFile(envPath, `${header}${additions.join('\n')}\n`, { mode: 0o600, flag: 'wx' });
  console.log('Created secure local .env configuration.');
} else if (additions.length) {
  const separator = existing.endsWith('\n') ? '' : '\n';
  await fs.appendFile(envPath, `${separator}\n# Added by ManeFlow 2.14 configuration migration\n${additions.join('\n')}\n`);
  console.log(`Updated existing .env with ${additions.length} missing ManeFlow setting(s).`);
} else {
  console.log('ManeFlow configuration already exists and is current: .env');
}

try { await fs.chmod(envPath, 0o600); } catch {}
console.log('Create the first account with memphiscardcompany@gmail.com to receive the administrator role.');
