import os from 'node:os';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, '..');
const packageMetadata = JSON.parse(fs.readFileSync(path.join(rootDir, 'package.json'), 'utf8'));

function boolean(value, fallback = false) {
  if (value === undefined || value === null || value === '') return fallback;
  return ['1', 'true', 'yes', 'on'].includes(String(value).toLowerCase());
}

export function loadConfig(env = process.env) {
  const port = Number(env.PORT || 4321);
  const publicBaseUrl = env.PUBLIC_BASE_URL || `http://localhost:${port}`;
  const releaseChannel = env.RELEASE_CHANNEL || 'desktop-beta';
  return {
    appName: 'ManeFlow',
    version: packageMetadata.version,
    releaseChannel,
    productionMode: env.NODE_ENV === 'production' || releaseChannel === 'production',
    port,
    host: env.HOST || '127.0.0.1',
    publicBaseUrl,
    storageMode: String(env.STORAGE_MODE || 'json').trim().toLowerCase(),
    databaseUrl: env.DATABASE_URL || '',
    databaseSsl: boolean(env.DATABASE_SSL, false),
    databasePoolMax: Math.max(1, Math.min(200, Number(env.DATABASE_POOL_MAX || 20))),
    databaseIdleTimeoutMs: Math.max(1_000, Number(env.DATABASE_IDLE_TIMEOUT_MS || 30_000)),
    databaseConnectTimeoutMs: Math.max(1_000, Number(env.DATABASE_CONNECT_TIMEOUT_MS || 10_000)),
    databaseStatementTimeoutMs: Math.max(100, Number(env.DATABASE_STATEMENT_TIMEOUT_MS || 15_000)),
    embeddingModelName: String(env.MANEFLOW_EMBEDDING_MODEL_NAME || 'siglip2-so400m-card-front-v1').trim(),
    embeddingModelVersion: String(env.MANEFLOW_EMBEDDING_MODEL_VERSION || '1').trim(),
    hnswEfSearch: Math.max(1, Math.min(10_000, Number(env.MANEFLOW_HNSW_EF_SEARCH || 100))),
    cacheMode: String(env.CACHE_MODE || (env.REDIS_URL ? 'redis' : 'memory')).trim().toLowerCase(),
    redisUrl: env.REDIS_URL || '',
    billingProvider: String(env.BILLING_PROVIDER || 'mock').trim().toLowerCase(),
    stripeSecretKey: env.STRIPE_SECRET_KEY || '',
    stripeWebhookSecret: env.STRIPE_WEBHOOK_SECRET || '',
    apiToken: env.MANEFLOW_API_TOKEN || '',
    serviceToken: env.MANEFLOW_SERVICE_TOKEN || '',
    adminToken: env.MANEFLOW_ADMIN_TOKEN || '',
    bootstrapAdminEmail: String(env.MANEFLOW_BOOTSTRAP_ADMIN_EMAIL || '').trim().toLowerCase(),
    demoMode: boolean(env.MANEFLOW_DEMO_MODE, true),
    requireAuthentication: boolean(env.MANEFLOW_REQUIRE_AUTHENTICATION, true),
    csrfProtection: boolean(env.MANEFLOW_CSRF_PROTECTION, true),
    allowLegacyAdminToken: boolean(env.MANEFLOW_ALLOW_LEGACY_ADMIN_TOKEN, false),
    allowGuestWrites: boolean(env.MANEFLOW_ALLOW_GUEST_WRITES, false),
    allowPublicSignups: boolean(env.MANEFLOW_ALLOW_PUBLIC_SIGNUPS, true),
    requireEmailVerification: boolean(env.MANEFLOW_REQUIRE_EMAIL_VERIFICATION, true),
    platformOwnerUserIds: String(env.MANEFLOW_PLATFORM_OWNER_USER_IDS || '').split(',').map((item) => item.trim()).filter(Boolean),
    ownerRecentReauthMinutes: Math.max(1, Math.min(60, Number(env.MANEFLOW_OWNER_RECENT_REAUTH_MINUTES || 15))),
    metaKillSwitch: boolean(env.MANEBRAIN_META_KILL_SWITCH, true),
    metaOutboundEnabled: boolean(env.MANEBRAIN_META_OUTBOUND_ENABLED, false),
    metaAppId: String(env.META_APP_ID || '').trim(),
    metaBusinessId: String(env.META_BUSINESS_ID || '').trim(),
    metaPageId: String(env.META_PAGE_ID || '').trim(),
    metaInstagramAccountId: String(env.META_INSTAGRAM_ACCOUNT_ID || '').trim(),
    exposeDevTokens: boolean(env.MANEFLOW_EXPOSE_DEV_TOKENS, false),
    accountTokenMinutes: Math.max(5, Math.min(1440, Number(env.MANEFLOW_ACCOUNT_TOKEN_MINUTES || 60))),
    emailWebhookUrl: String(env.MANEFLOW_EMAIL_WEBHOOK_URL || '').trim(),
    emailWebhookSecret: String(env.MANEFLOW_EMAIL_WEBHOOK_SECRET || '').trim(),
    sessionDays: Math.max(1, Math.min(365, Number(env.MANEFLOW_SESSION_DAYS || 30))),
    allowedOrigins: String(env.ALLOWED_ORIGINS || '').split(',').map((item) => item.trim()).filter(Boolean),
    remoteImageHosts: String(env.MANEFLOW_REMOTE_IMAGE_HOSTS || '').split(',').map((item) => item.trim()).filter(Boolean),
    cardImageAllowedHosts: String(env.MANEFLOW_CARD_IMAGE_ALLOWED_HOSTS || '').split(',').map((item) => item.trim()).filter(Boolean),
    cardImageTemplate: String(env.MANEFLOW_CARD_IMAGE_TEMPLATE || '').trim(),
    cardImageSource: String(env.MANEFLOW_CARD_IMAGE_SOURCE || '').trim(),
    cardImageRightsNotes: String(env.MANEFLOW_CARD_IMAGE_RIGHTS_NOTES || '').trim(),
    maxRequestBytes: Math.max(1_000_000, Number(env.MAX_REQUEST_BYTES || 14_000_000)),
    runtimeFile: env.MANEFLOW_STATE_FILE || path.join(rootDir, '.runtime/state.json'),
    localOcrEnabled: boolean(env.MANEFLOW_LOCAL_OCR_ENABLED, true),
    localOcrProvider: String(env.MANEFLOW_LOCAL_OCR_PROVIDER || 'auto').trim().toLowerCase(),
    localOcrQueueCapacity: Math.max(1, Math.min(32, Number(env.MANEFLOW_LOCAL_OCR_QUEUE_CAPACITY || 4))),
    localOcrTimeoutMs: Math.max(1_000, Math.min(120_000, Number(env.MANEFLOW_LOCAL_OCR_TIMEOUT_MS || 20_000))),
    openaiApiKey: env.OPENAI_API_KEY || '',
    openaiVisionModel: env.OPENAI_VISION_MODEL || '',
    visionWorkerUrl: String(env.MANEFLOW_VISION_WORKER_URL || 'http://127.0.0.1:8741').replace(/\/+$/, ''),
    visionWorkerTimeoutMs: Math.max(5_000, Number(env.MANEFLOW_VISION_WORKER_TIMEOUT_MS || 120_000)),
    providerWebhookSecret: env.PROVIDER_WEBHOOK_SECRET || '',
    ebayClientId: env.EBAY_CLIENT_ID || '',
    ebayClientSecret: env.EBAY_CLIENT_SECRET || '',
    ebayMarketplaceInsightsEnabled: boolean(env.EBAY_MARKETPLACE_INSIGHTS_ENABLED, false),
    ebayUserAccessToken: env.EBAY_USER_ACCESS_TOKEN || '',
    ebayUserAccessTokenExpiresAt: Number(env.EBAY_USER_ACCESS_TOKEN_EXPIRES_AT || 0),
    ebayRefreshToken: env.EBAY_REFRESH_TOKEN || '',
    ebayRedirectUriName: env.EBAY_REDIRECT_URI_NAME || '',
    ebayOauthStateSecret: env.EBAY_OAUTH_STATE_SECRET || '',
    ebayOauthStateTtlMs: Math.max(60_000, Math.min(30 * 60_000, Number(env.EBAY_OAUTH_STATE_TTL_MS || 600_000))),
    ebayUserScopes: String(env.EBAY_USER_SCOPES || 'https://api.ebay.com/oauth/api_scope https://api.ebay.com/oauth/api_scope/sell.fulfillment.readonly').split(/[\s,]+/).map((item) => item.trim()).filter(Boolean),
    ebayMarketplaceId: env.EBAY_MARKETPLACE_ID || 'EBAY_US',
    ebayEnvironment: env.EBAY_ENVIRONMENT || 'production',
    ebayRequestTimeoutMs: Math.max(3000, Number(env.EBAY_REQUEST_TIMEOUT_MS || 15000)),
    ebayMaxRetries: Math.max(0, Math.min(5, Number(env.EBAY_MAX_RETRIES || 3))),
    ebayMinBackoffMs: Math.max(100, Number(env.EBAY_MIN_BACKOFF_MS || 400)),
    justTcgApiKey: env.JUSTTCG_API_KEY || '',
    justTcgBaseUrl: env.JUSTTCG_BASE_URL || 'https://api.justtcg.com/v1',
    justTcgTimeoutMs: Math.max(3000, Number(env.JUSTTCG_TIMEOUT_MS || 15000)),
    sportsCardsProApiToken: env.SPORTSCARDSPRO_API_TOKEN || '',
    sportsCardsProBaseUrl: env.SPORTSCARDSPRO_BASE_URL || 'https://www.sportscardspro.com',
    sportsCardsProTimeoutMs: Math.max(3000, Number(env.SPORTSCARDSPRO_TIMEOUT_MS || 15000)),
    tcgplayerPublicKey: env.TCGPLAYER_PUBLIC_KEY || '',
    tcgplayerPrivateKey: env.TCGPLAYER_PRIVATE_KEY || '',
    desktopDefaultMode: env.MANEFLOW_DESKTOP_MODE || 'cloud',
    widgetAllowedOrigins: String(env.MANEFLOW_WIDGET_ALLOWED_ORIGINS || env.ALLOWED_ORIGINS || '').split(',').map((item) => item.trim()).filter(Boolean),
    hostname: os.hostname(),
    secureCookies: publicBaseUrl.startsWith('https://'),
    releaseCommitSha: String(env.RELEASE_COMMIT_SHA || 'unverified').trim(),
    releaseDeployedAt: String(env.RELEASE_DEPLOYED_AT || '').trim(),
    releaseEnvironment: String(env.RELEASE_ENVIRONMENT || releaseChannel).trim(),
    webReleaseId: String(env.MANEFLOW_WEB_RELEASE_ID || env.WEB_RELEASE_ID || '').trim(),
    apiReleaseId: String(env.MANEFLOW_API_RELEASE_ID || env.API_RELEASE_ID || '').trim(),
    visionReleaseId: String(env.MANEFLOW_VISION_RELEASE_ID || env.VISION_RELEASE_ID || '').trim(),
    migrationVersion: String(env.MANEFLOW_MIGRATION_VERSION || env.MIGRATION_VERSION || '005').trim(),
  };
}
